### ISSUE TITLE
Use LD_LIBRARY_PATH for rocm shared library loaded

### ISSUE THREAD

**Issue by hodgesds** [PTFOPlayer/rocm_lib_sys#1]
Can the [default](https://github.com/PTFOPlayer/rocm_lib_sys/blob/master/src/lib.rs#L7) instead search the `LD_LIBRARY_PATH`? I think that would make this library more useful by default.

**Comment by PTFOPlayer** [comment]
Yes it can

I'm not sure why I didn't think of that...

You are welcome to open PR or wait for me to figure it out.

**Comment by PTFOPlayer** [comment]
Issue closed, i forgot to push fix like two months ago
