### ISSUE TITLE
get_pcie_data returns a RsmiStatusUnexpectedData exception

### ISSUE THREAD

**Issue by hodgesds** [PTFOPlayer/rocm_lib_sys#2]
Not sure if I'm using the [get_pcie_data](https://docs.rs/rocm_smi_lib/0.2.3/rocm_smi_lib/device/struct.RocmSmiDevice.html#method.get_pcie_data) method correctly, but it seems to be throwing an exception any time I try to use it:
```
called `Result::unwrap()` on an `Err` value: RsmiStatusUnexpectedData
 ```
 I am able to get data directly with `rocm-smi`:
 ```
=================================== Current Memory Use ===================================                                                                                   23:22:23 [115/9050]
GPU[0]          : GPU memory use (%): 2
GPU[0]          : Memory Activity: N/A
GPU[0]          : Avg. Memory Bandwidth: 0
GPU[1]          : % memory use, Not supported on the given system
GPU[1]          : Memory Activity: N/A
GPU[1]          : Not supported on the given system
==========================================================================================
===================================== Memory Vendor ======================================
GPU[0]          : GPU memory vendor: hynix
GPU[1]          : get_vram_vendor, Not supported on the given system
==========================================================================================
================================== PCIe Replay Counter ===================================
GPU[0]          : PCIe Replay Count: 0
GPU[1]          : PCIe Replay Count: 0
========================================================
```

**Comment by PTFOPlayer** [comment]
I see you have two GPU. What models are those and can you share how you use this function.

**Comment by hodgesds** [comment]
One is an iGPU (Ryzen 7600X) and the other is a Radeon 6700XT. I'm working on making [BPF schedulers](https://github.com/sched-ext/scx) aware of GPUs ([branch](https://github.com/sched-ext/scx/commit/f79bb02178a63b69fcab9720aad6266bf74cec04)).

**Comment by PTFOPlayer** [comment]
Unfortunately it looks like I will be changing how PCIE API works.

For now inside get_pcie_data are 5 function calls and if one of them fails then the whole function fails.

It will be changed so every function returns separate error in one struct

**Comment by hodgesds** [comment]
I was able to get some pcie data:
```
gpu Identifiers { id: Ok(29663), revision: Ok(192), vendor_id: Ok(4098), name: Ok("Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]"), brand: Ok("Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]"), vendor_name: Ok("Advanced Micro Devices, Inc. [AMD/ATI]"), vram_vendor_name: Ok("hynix"), serial_number: Err(RsmiStatusNotSupported), subsystem_id: Ok(14725), subsystem_name: Ok("0x3985"), drm_render_minor: Ok(128), subsystem_vendor_id: Ok(5218), unique_id: Err(RsmiStatusNotSupported), xgmi_physical_id: Err(RsmiStatusNotSupported) }
pcie gpu Pcie { id: 768, associated_numa_node: 4294967295, current_index: 2, lanes: [], frequency: [], pkg_sent: 4294967295, pkg_recived: 0, max_pkg_size: 0 }
```
However, the `associated_numa_node` node id doesn't match my system either.
```
lscpu | grep -i numa
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-11
```

Thanks for looking into this!

**Comment by PTFOPlayer** [comment]
There was issue with types (must have changed in recent version of ROCM SMI c liblary) so i fixed it but it still seems to be broken

I also implemented [rsmi_topo_get_numa_node_number](https://rocm.docs.amd.com/projects/rocm_smi_lib/en/latest/doxygen/html/group__HWTopo.html#ga99bdcce451e3c64123b9cde07f56d23c) as [get_topo_numa_node_number](https://docs.rs/rocm_smi_lib/0.2.4/rocm_smi_lib/device/struct.RocmSmiDevice.html#method.get_topo_numa_node_number), that function should give you correct numa node id, unfortunately i have no way to test it myself right now as i don't have system with non uniform memory

feel free to do some testing and open more issues if you find something else broken

**Comment by hodgesds** [comment]
Thank you so much for taking a look! I'll test again later when I'm at home.
